version: '3.4'

services:
  oathkeeper:
    build: 
      context: ./oathkeeper/
    hostname: oathkeeper
    ports:
      - "4455:4455"
      - "4456:4456"
    command:
        serve --config=/config.yaml